### ISSUE TITLE
Error when import : Cannot use object of type WP_Post as array

### ISSUE THREAD

**Issue by tchama** [eriktorsner/wp-bootstrap#4]
I create new WP with wp-cli/wp-bootstrap. 
Then I attach a picture in a page, export (wp bootstrap export) and try to re-import all contents. 
But i have this error : 
```
tcha@totoro:~/public_html/wp/1611_jayal$ wp bootstrap import --debug
Debug (bootstrap): Using default global config: /home/tcha/.wp-cli/config.yml (0.006s)
Debug (bootstrap): Using project config: /home/tcha/public_html/wp/1611_jayal/wp-cli.yml (0.006s)
Debug (bootstrap): Loading packages from: /home/tcha/.wp-cli/packages/vendor/autoload.php (0.026s)
Debug (bootstrap): Required file from config: /home/tcha/public_html/wp/1611_jayal/vendor/autoload.php (0.032s)
Debug (bootstrap): ABSPATH defined: /home/tcha/public_html/wp/1611_jayal/www/ (0.032s)
Debug (bootstrap): Begin WordPress load (0.032s)
Debug (bootstrap): wp-config.php path: /home/tcha/public_html/wp/1611_jayal/www/wp-config.php (0.032s)
Debug (bootstrap): Loaded WordPress (0.257s)
Debug (bootstrap): Running command: bootstrap import (0.257s)
Importing settings
Importing content
Debug: Importing posts (1.911s)
Debug: Media is attached to post 11 2 (2.15s)
PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Post as array in /home/tcha/public_html/wp/1611_jayal/vendor/eriktorsner/wp-bootstrap/src/Import/ImportPosts.php:204
Stack trace:
#0 /home/tcha/public_html/wp/1611_jayal/vendor/eriktorsner/wp-bootstrap/src/Import/ImportPosts.php(91): Wpbootstrap\Import\ImportPosts->importMedia()
#1 /home/tcha/public_html/wp/1611_jayal/vendor/eriktorsner/wp-bootstrap/src/Import/ImportPosts.php(58): Wpbootstrap\Import\ImportPosts->internalImport()
#2 /home/tcha/public_html/wp/1611_jayal/vendor/eriktorsner/wp-bootstrap/src/Commands/Import.php(88): Wpbootstrap\Import\ImportPosts->import()
#3 /home/tcha/.wp-cli/packages/vendor/eriktorsner/wp-bootstrap/src/Bootstrap.php(99): Wpbootstrap\Commands\Import->run(Array, Array)
#4 [internal function]: Wpbootstrap\Bootstrap->import(Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#6 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array in /home/tcha/public_html/wp/1611_jayal/vendor/eriktorsner/wp-bootstrap/src/Import/ImportPosts.php on line 204
```
I finaly found that it works when i change ImportPosts.php on line 204
```
--- $id = $existing->post['ID'];
+++  $id = $existing->post->ID; 
```
And it seems to work better :
```
Importing settings
Importing content
Debug: Importing posts (1.948s)
Debug: Media is attached to post 11 2 (2.193s)
Debug: Importing taxonomies (2.194s)
Debug: Importing term Non classé/non-classe parent: 0 (2.195s)
Debug: Importing menus (2.488s)
Debug: Importing sidebars (4.654s)
Debug: Assigning objects to taxonomies (4.654s)
Debug: adding terms to post bonjour-tout-le-monde (4.654s)
Resolving references
```
Could you check my patch,  and commit  ?
Thank you for wp-bootstrap.

**Comment by eriktorsner** [comment]
Hi tchama,

Thanks for the PR. I'll review asap.

**Comment by eriktorsner** [comment]
The PR is merged. Many thanks for the input
